import { Inter } from 'next/font/google'
import {Government_provider} from '@/context/GovernanceContext'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Government_provider>
          {children}
        </Government_provider>
      </body>
    </html>
  )
}
